### PR TITLE
WIP Rewrite to use phpstan for guessing variable types

### LINKED ISSUE #40: Type inferencing
A lot of upgrade sniffs will be about particular methods being called on particular classes. To support this, a useful support class in the php-parser would be a type inferencing system, that would augment the AST with type hints before passing on to other more specific checks.

A few thoughts on implementation:

 * The general way that you can do this is do iterative run a pass over things that bubbles type information one step forward, and stops when a single pass is a no-op
 * As well as PHP-generic type information being passed, it would be useful to be able to pass in framework-specific knowledge, for example about Injector::inst()->get().
 * It should read docblock type information
 * The AST may not have space to include this meta-data; it's an open question as to how this data is stored.

This could possibly be a micropackage separate from silverstripe-upgrader, as it may be of use to other users of php-parser.

### LINKED ISSUE #49: Upgrader adds namespace decleration to Page.php and PageController.php
According to https://docs.silverstripe.org/en/4/upgrading/ "The Page and PageController classes must be defined in the global namespace"

Running "~/.config/composer/vendor/bin/upgrade-code add-namespace "OurCo\NAME" NAME/mysite/code/ --write"

Puts Page and PageController into namespaces

### LINKED ISSUE #53: Upgrader should put .upgrade.yml into vendorised module folder
Say I have a module in `vendor/monkey/bar` and I want to add "Monkey\Bar\Foo" to `vendor/monkey/bar/src/Foo`, I'd run this from my project:

```
upgrade-code add-namespace "Monkey\Bar\Foo" vendor/monkey/bar/src/Foo --write
```

This will create an .upgrade.yml file at `vendor/.upgrade.yml` which is incorrect.

It looks like the rules are "create .upgrade.yml file in the folder above the current working directory" which would have worked as expected when running this without vendorised modules.

Perhaps we need to add an argument to customise the directory that the .upgrade.yml is written to?

### LINKED ISSUE #54: Running `upgrade` should work with `silverstripe-vendormodule` applied code.
Currently the tool doesn't really work too well when trying to upgrade a module (see #53 ), but once working around this issue the `upgrade` command does not work as expected.

Running `upgrade-code upgrade` (after adding namespaces) in various directories results in:
Webroot:
```
$ upgrade-code upgrade
Running upgrades on "C:\Users\testing\work\testymctestface"
[2017-11-22 15:11:48] Applying RenameClasses to IFramePage.php...
[2017-11-22 15:11:49] Applying RenameClasses to IFramePageController.php...
[2017-11-22 15:11:49] Applying RenameClasses to IFramePageTest.php...
[2017-11-22 15:11:49] Applying RenameClasses to _config.php...
[2017-11-22 15:11:49] Applying RenameClasses to index.php...
[2017-11-22 15:11:49] Applying RenameClasses to install.php...
[2017-11-22 15:11:49] Applying RenameClasses to Page.php...
[2017-11-22 15:11:49] Applying RenameClasses to PageController.php...
[2017-11-22 15:11:49] Applying RenameClasses to _config.php...
[2017-11-22 15:11:49] Applying RenameClasses to config.php...
[2017-11-22 15:11:49] Applying RenameClasses to server.php...
[2017-11-22 15:11:49] Applying RenameClasses to class.tree.php...
[2017-11-22 15:11:49] Applying RenameClasses to class._database.php...
[2017-11-22 15:11:49] Applying RenameClasses to class._database_i.php...
[2017-11-22 15:11:50] Applying RenameClasses to tiny_mce_gzip.php...
Changes not saved; Run with --write to commit to disk
```
Webroot, with specifying a path:
- vendor
- vendor/silverstripe
- vendor/silverstripe/externallinks
- vendor/silverstripe/externallinks/src

All return the same result, e.g.
```
Running upgrades on "C:\Users\testing\work\testymctestface\vendor\silverstripe\externallinks\src"
Changes not saved; Run with --write to commit to disk
```
Running the command from within each of those folders, with varying paths all also return the same result, or:
```
  [InvalidArgumentException]
  No .upgrade.yml definitions found in modules on "C:\Users\testing\work\te
  stymctestface\vendor\externallinks". Please ensure you upgrade your SilverStripe dependen
  cies before running this task.
```
despite:
```
$ pwd && ls .u*
/c/Users/testing/work/testymctestface/vendor/silverstripe/externallinks
.upgrade.yml
```

### LINKED ISSUE #58: The "--recursive" option does not exist.
When I try (according to the [README](https://github.com/silverstripe/silverstripe-upgrader#upgrading-code))

> upgrade-code upgrade my-module/ --write --recursive

I get

>   [Symfony\Component\Console\Exception\RuntimeException]
  The "--recursive" option does not exist.

### PR DESCRIPTION
**Pull request by tractorcow**
Parent story https://github.com/silverstripe/silverstripe-upgrader/issues/51

Fixes #40
Fixes #49 
Fixes #53
Fixes #54
Fixes #58

### CODE REVIEW

File: src/UpgradeRule/PHP/Visitor/SymbolContextVisitor.php [hunk 1]
```diff
@@ -124,7 +147,8 @@ public function enterNode(Node $node)
                 'namespace' => $this->namespace,
                 'uses' => $this->uses,
                 'class' => $this->parentClass,
-                'staticClass' => $staticClass,
+                'staticClass' => $staticClass, // class in TheClass::
+                'instanceClass' => $instanceClass, // class for type of $var->
```
Comment (tractorcow) [inline src/UpgradeRule/PHP/Visitor/SymbolContextVisitor.php]: Finally got this bit working ;)

**Comment by robbieaverill** [comment]
Side note: do you think we could use this kind of library for rewriting the text collector?

**Comment by tractorcow** [comment]
php parser would be, but none of the work i'm doing in this PR would be useful.
