### PR TITLE
BUG Fix unnecessary "use" aliases being added to classes in the same namespace but another file

### LINKED ISSUE #7: Doesn't handle other classes in same namespace properly
If you just run `add-namespace`, depending on order it doesn't know about the other classes that are also being moved into same namespace. So for instance, even though DB and DataObject are both being moved into SilverStripe\ORM, in DataObject there is a `use DB;` statement introduced.

If you then run `upgrade`, it will remove the `use DB;` statement and add a `use SilverStripe\ORM\DB;` instead. While this is "right" (in that it won't break anything), it's "wrong" in that it's redundant. Also, ugly empty lines are left from where the (un-needed) `use DB;` statement was removed.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #7

### CODE REVIEW

File: src/UpgradeRule/AbstractUpgradeRule.php [hunk 1]
```diff
@@ -15,6 +17,26 @@
     protected $warningCollector = [];
 
     /**
+     * Called on a code collection prior to upgrade
+     *
+     * @param CollectionInterface $code
+     * @param CodeChangeSet $changeset
+     */
+    public function beforeUpgrade(CollectionInterface $code, CodeChangeSet $changeset)
```
Comment (sminnee) [inline src/UpgradeRule/AbstractUpgradeRule.php]: Maybe `beforeUpgradeCollection()` and `afterUpgradeCollection()` are better names? If someone was upgrading a single file they might not call this.

File: src/UpgradeRule/AddNamespaceRule.php [hunk 2]
```diff
@@ -77,6 +79,43 @@ public function withRoot($root)
         return $this;
     }
 
+
+    public function beforeUpgrade(CollectionInterface $code, CodeChangeSet $changeset)
```
Comment (sminnee) [inline src/UpgradeRule/AddNamespaceRule.php]: Maybe make this the default implementation and leave `beforeUpgradeFile()` as the empty function to be overridden?

File: src/UpgradeRule/AbstractUpgradeRule.php (hunk 1 above)
Comment (sminnee) [inline src/UpgradeRule/AbstractUpgradeRule.php]: Do we actually need the CodeChangeSet here? I'm not sure what people would expect to put in it?

File: src/UpgradeRule/AddNamespaceRule.php [hunk 3]
```diff
@@ -77,6 +79,43 @@ public function withRoot($root)
...
+        }
+
+        // Add classes in this file to namespace mapping
+        $newNamespace = $this->getNamespaceForFile($file);
+        foreach ($fileClasses as $class) {
+            $this->renamedClasses[$class] = "{$newNamespace}\\{$class}";
+        }
+    }
+
     public function upgradeFile($contents, $file)
```
Comment (sminnee) [inline src/UpgradeRule/AddNamespaceRule.php]: We want to amend the call approach here to more closely match the before handlers. Maybe pass an ItemInterface and a CodeChangeSet to populate?

File: src/UpgradeRule/AbstractUpgradeRule.php (hunk 1 above)
Comment (tractorcow) [inline src/UpgradeRule/AbstractUpgradeRule.php]: In case upgraders need to add warnings before/after.

File: src/UpgradeRule/AddNamespaceRule.php (hunk 2 above)
Comment (tractorcow) [inline src/UpgradeRule/AddNamespaceRule.php]: I'm not assuming that all "before upgrade" tasks are done on a per-file basis. It only is in this case.

File: src/UpgradeRule/AddNamespaceRule.php (hunk 3 above)
Comment (tractorcow) [inline src/UpgradeRule/AddNamespaceRule.php]: Yeah I think so; That way it can add warnings directly, rather than having to return it.
